### ISSUE TITLE
Unrelated to this project

### ISSUE THREAD

**Issue by ToonMods** [ThatFruedDued/JustSomeRandomFiles#1]
Do you still have your gimki script?

I was using it and it was very helpful, but I cant seem to find it now. Any chance you could send it my way?

Thanks!

**Comment by UndercoverGoose** [comment]
I am the original creator of the Gimkit hack script. ThatFruedDued has an older version of it.
Link: [https://github.com/UndercoverGoose/quizlet/blob/master/gimkit.js](url)

It may pop up that something saying the site is deceptive, just click "Details" and "Visit this unsafe side" to run the scripts.

**Comment by UndercoverGoose** [comment]
Also, if you want the bookmarklet that runs the code automatically, here you go:
`javascript:let lscrp=document.createElement('script');lscrp.src="https://undercovergoose.github.io/quizlet/gimkit.js";document.body.appendChild(lscrp);void 0`

**Comment by ToonMods** [comment]
Thanks mate.

**Comment by FloppyT** [comment]
Cheating in gimkit is no longer allowed and is against the ToS, also the hack you have listed is slow, outdated, and no longer works.
